{% set name = "oqpy" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oqpy-{{ version }}.tar.gz
  sha256: 33769e27710d3441a5596a4cb21c16b726b2a85ece3b674910a8da07e2f99bae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7,<3.11
    - mypy_extensions >=0.4.3,<0.5.0
    - numpy >=1.21.6,<2.0.0
    - openpulse >=0.4.0,<0.5.0
    - typing-extensions >=4.3.0,<5.0.0

test:
  imports:
    - oqpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openqasm/oqpy
  summary: Generating OpenQASM 3 + OpenPulse in Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
