{% set name = "oqpy" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oqpy-{{ version }}.tar.gz
  sha256: ecc955b940334c8ee2ab157718ba6a10cd05f4f1442ee9d1519188965699e83b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7,<4.0
    - mypy_extensions >=0.2.0
    - numpy >=1.14.5
    - openpulse >=0.4.2
    - typing-extensions >=3.10.0.2

test:
  imports:
    - oqpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openqasm/oqpy
  summary: Generating OpenQASM 3 + OpenPulse in Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
